backend:
  name: github
  repo: stanhuan/pwa-demo

media_folder: static/assets

collections:
  - name: sponsors
    label: Sponsors
    folder: sponsors
    create: true
    fields:
      - name: name
        label: Name
      - name: photo
        label: Photo
        widget: image
      - name: website
        label: Website
      - name: level
        label: Level
        widget: select
        options: [startup, bronze, silver, gold]
  - label: FAQs
    name: faqs
    folder: faqs
    create: true
    widget: list
    fields:
      - {label: Section, name: section, widget: string}
      - label: faq
        name: FAQ
        widget: list
        fields:
          - {label: Question, name: question, widget: string}
          - {label: Answer, name: answer, widget: string}
